backend:
  - 'casadi'  # [linux or osx and py<38]
  - 'eigen'

rbdl_variant:
  - 'rbdl =*=casadi*'  # [linux or osx and py<38]
  - 'rbdl'
  
backend_name_in_build:
  - 'Casadi'  # [linux or osx and py<38]
  - 'Eigen3'
  
zip_keys:
-
  - backend
  - rbdl_variant
  - backend_name_in_build
