{% set name = "biorbd" %}
{% set version = "1.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pyomeca/{{ name }}/archive/Release_{{ version }}.tar.gz
  sha256: bb08e1c43738d28c2756f05cff32a818ccf1c724b21d901de72ba27b0198d1f1

build:
  number: 0
  skip: true  # [win and vc<14]
  skip: true  # [py<35]
  rpaths:
    - lib/
    - lib/{{ name }}/
  run_exports:
    - {{ pin_subpackage('biorbd', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - eigen
    - rbdl
    - tinyxml
    - ipopt  # [not win]
    - python
    - numpy
    - swig
  run:
    - {{ pin_compatible('rbdl') }}
    - ipopt  # [not win]
    - python
    - {{ pin_compatible('numpy') }}

test:
  commands:
    - test -f $PREFIX/lib/biorbd/libbiorbd$SHLIB_EXT  # [unix]
    - if not exist %PREFIX%\\Lib\\biorbd*.lib exit 1  # [win]
  imports:
    - biorbd

about:
  home: http://github.com/pyomeca/biorbd
  license: MIT
  license_file: LICENSE
  summary: 'Biomechanical add-ons to the RigidBody Dynamics Library '

  description: |
    Biomechanical add-ons to the RigidBody Dynamics Library .
  doc_url: https://github.com/pyomeca/biorbd/
  dev_url: https://github.com/pyomeca/biorbd/

extra:
  recipe-maintainers:
    - pariterre
