{% set name = "biorbd" %}
{% set version = "1.3.1" %}
{% set build_num = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pyomeca/{{ name }}/archive/Release_{{ version }}.tar.gz
  sha256: e5fb1a092f5b064eb303a2d416efe449f25146d73eebd245540c6c97e9f8732e

build:
  number: {{ build_num }}
  skip: true  # [win and vc<14]
  rpaths:
    - lib/
    - lib/{{ name }}/
  run_exports:
    - {{ pin_subpackage('biorbd', max_pin='x.x') }}
    - biorbd * {{ backend }}_*
  string: py{{ py }}_{{ backend }}_h{{ PKG_HASH }}_{{ build_num }}
  track_features:
    - casadi  # [backend == "casadi"]
requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - rbdl =*=*casadi*  # [backend == "casadi"]
    - rbdl  # [backend == "eigen"]
    - tinyxml
    - ipopt  # [not win]
    - python
    - numpy  # [backend == "eigen"]
    - swig
  run:
    - {{ pin_compatible('rbdl') }}  # [backend == "casadi" and not osx]
    - rbdl =*=casadi*   # [backend == "casadi" and osx]
    - rbdl  # [backend == "eigen"]
    - ipopt  # [not win]
    - python
    - {{ pin_compatible('numpy') }}  # [backend == "eigen"]

test:
  commands:
    - test -f $PREFIX/lib/biorbd/libbiorbd$SHLIB_EXT  # [unix]
    - if not exist %PREFIX%\\Lib\\biorbd*.lib exit 1  # [win]
  imports:
    - biorbd

about:
  home: http://github.com/pyomeca/biorbd
  license: MIT
  license_file: LICENSE
  summary: 'Biomechanical add-ons to the RigidBody Dynamics Library '

  description: |
    Biomechanical add-ons to the RigidBody Dynamics Library .
  doc_url: https://github.com/pyomeca/biorbd/
  dev_url: https://github.com/pyomeca/biorbd/

extra:
  recipe-maintainers:
    - pariterre
