travis:
  secure:
    BINSTAR_TOKEN: LxNZN6KcdmlTrYfaXoZzyXUCVwz5leUFltuJrj1qNGGtBJD5AKOySTCar8TslxCfS+hVQn6B7/CU9I4HMBbs2VO7s9epbzUCIX9IU929T1/vwQLa3NHeGh9vRKz6/tsqHzrcNdy2xpqj8FsjJeWA9M+iAooVuu9P2LmRFv8wllznfjfokWI8h9zmhDQUKt8H4K1ZomM9HQRiKhZ3dyaY29A2aoIgyAMtmnl/QV5KOBZbcaTajDaT7eFX3Takq12pfRzsf2YiDL9hRyJp039A5l+ElHC5TJQCoyO65ESY0zx+pbjpyNMlmojHAOJnupnSxZFDN+6jKavWnmo+ePz80eA40Zii/SS9CYj4LGg6erg33huABjDiAj6gxHl1kIY1MA9bFLQ27MrRMpl35HaTMO775SEvu3XrzgOkwM8QHPI1JkLA5PZq5RyTmPSqcRDkNRZe0dPomtrmGtP5KUNwmkB5PEk7GjwUXE07gnvTe8y81gtGXbs+TB1bi53IjtdHU1PbjVYVDb8ITQHDxx5dQE+pvWLXqG8st8c7TEDLifxhq9qfU4TLe8EvXAELOBE25/okhc016rI1UazuOYAxpoip2ZXL0k7n/SdxRg3Ule81DB3trX0ijdgZbT8pMeyNpJUGH7elSUwXFbeYUhln29wpMruYVgMuZ94Nuf6u0O4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: appveyor
